# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- test
- release
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
- template: Security/Dependency-Scanning.gitlab-ci.yml
- template: Security/Secret-Detection.gitlab-ci.yml
release:
  stage: release
  image: docker:stable
  services:
  - docker:dind
  variables:
    DOCKER_REGISTRY: "$CI_REGISTRY"
    DOCKER_USERNAME: "$CI_REGISTRY_USER"
    DOCKER_PASSWORD: "$CI_REGISTRY_PASSWORD"
    GIT_DEPTH: 0
  only:
    refs:
    - tags
  script: |
    docker run --rm --privileged \
      -v $PWD:/go/src/gitlab.com/pmoscodegrp/tarpit-analyzer \
      -w /go/src/gitlab.com/pmoscodegrp/tarpit-analyzer \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e DOCKER_USERNAME -e DOCKER_PASSWORD -e DOCKER_REGISTRY  \
      -e GITLAB_TOKEN \
      -e CGO_ENABLED=1 \
      ghcr.io/troian/golang-cross:v1.17.4 release --rm-dist
