project_name: Tarpit-Analyzer
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
#dockers:
#- image_templates: ["registry.gitlab.com/pmoscode/tarpit-analyzer:{{ .Version }}"]
#  dockerfile: Dockerfile
#  build_flag_templates:
#  - --label=org.opencontainers.image.title={{ .ProjectName }}
#  - --label=org.opencontainers.image.description={{ .ProjectName }}
#  - --label=org.opencontainers.image.url=https://gitlab.com/pmoscode/tarpit-analyzer
#  - --label=org.opencontainers.image.source=https://gitlab.com/pmoscode/tarpit-analyzer
#  - --label=org.opencontainers.image.version={{ .Version }}
#  - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
#  - --label=org.opencontainers.image.revision={{ .FullCommit }}
#  - --label=org.opencontainers.image.licenses=GPLv3
nfpms:
- maintainer: pmoscode <ifo@pmoscode.de>
  description: Tarpit Analyzer
  homepage: https://gitlab.com/pmoscode/tarpit-analyzer
  license: GPLv3
  formats:
  - deb
  - rpm
