project_name: tarpit-analyzer
builds:
  - id: linux-amd64
    env:
      - CC=gcc
      - CXX=g++
    goos:
      - linux
    goarch:
      - amd64
  - id: windows-amd64
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
nfpms:
- maintainer: pmoscode <info@pmoscode.de>
  description: Tarpit Analyzer
  homepage: https://gitlab.com/pmoscodegrp/tarpit-analyzer
  license: GPLv3
  formats:
  - deb
  - rpm
