version: '3'

tasks:
  upgrade:
    desc: Update go dependencies
    cmds:
      - go get -u .

  build:
    desc: Build the binary
    cmd: go build .

  clean:
    desc: Cleanup dependencies
    cmd: go mod tidy